// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/api/backgrounds/telemetry": {
    params: {};
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/api/test-digital-submenu": {
    params: {};
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/api/backgrounds/active": {
    params: {};
  };
  "/api/backgrounds": {
    params: {};
  };
  "/api/products-3d-simple": {
    params: {};
  };
  "/api/backgrounds/token": {
    params: {};
  };
  "/api/backgrounds/:id": {
    params: {
      "id": string;
    };
  };
  "/api/backgrounds/:id/activate": {
    params: {
      "id": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/api/admin/config": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/api/products-3d": {
    params: {};
  };
  "/api/test-client": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/favicon.ico": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/product": {
    params: {};
  };
  "/api/test-3d": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs/:blogHandle/:articleHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/:locale?/sitemap/:type/:page.xml": {
    params: {
      "locale"?: string;
      "type": string;
      "page": string;
    };
  };
  "/:locale?/blogs/:blogHandle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
    };
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/authorize": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/logout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections/all": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/login": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discount/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/sitemap.xml": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/addresses": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/profile": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/api/page": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/search": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/api/backgrounds/telemetry" | "/sitemap/:type/:page.xml" | "/api/test-digital-submenu" | "/blogs/:blogHandle" | "/api/backgrounds/active" | "/api/backgrounds" | "/api/products-3d-simple" | "/api/backgrounds/token" | "/api/backgrounds/:id" | "/api/backgrounds/:id/activate" | "/collections/:handle" | "/account/authorize" | "/collections" | "/api/admin/config" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/api/products-3d" | "/api/test-client" | "/collections/all" | "/policies" | "/account/login" | "/discount/:code" | "/favicon.ico" | "/pages/:handle" | "/sitemap.xml" | "/blogs" | "/robots.txt" | "/api/product" | "/api/test-3d" | "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*" | "/api/page" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/search" | "/admin" | "/cart" | "/cart/:lines" | "/*";
  };
  "./layout.jsx": {
    id: "layout";
    page: "/blogs/:blogHandle/:articleHandle" | "/api/backgrounds/telemetry" | "/sitemap/:type/:page.xml" | "/api/test-digital-submenu" | "/blogs/:blogHandle" | "/api/backgrounds/active" | "/api/backgrounds" | "/api/products-3d-simple" | "/api/backgrounds/token" | "/api/backgrounds/:id" | "/api/backgrounds/:id/activate" | "/collections/:handle" | "/account/authorize" | "/collections" | "/api/admin/config" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/api/products-3d" | "/api/test-client" | "/collections/all" | "/policies" | "/account/login" | "/discount/:code" | "/favicon.ico" | "/pages/:handle" | "/sitemap.xml" | "/blogs" | "/robots.txt" | "/api/product" | "/api/test-3d" | "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*" | "/api/page" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/search" | "/" | "/admin" | "/cart" | "/cart/:lines" | "/*";
  };
  "routes/blogs.$blogHandle.$articleHandle.jsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/api.backgrounds.telemetry.tsx": {
    id: "routes/api.backgrounds.telemetry";
    page: "/api/backgrounds/telemetry";
  };
  "routes/sitemap.$type.$page[.xml].jsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/api.test-digital-submenu.jsx": {
    id: "routes/api.test-digital-submenu";
    page: "/api/test-digital-submenu";
  };
  "routes/blogs.$blogHandle._index.jsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/api.backgrounds.active.tsx": {
    id: "routes/api.backgrounds.active";
    page: "/api/backgrounds/active";
  };
  "routes/api.backgrounds._index.tsx": {
    id: "routes/api.backgrounds._index";
    page: "/api/backgrounds";
  };
  "routes/api.products-3d-simple.jsx": {
    id: "routes/api.products-3d-simple";
    page: "/api/products-3d-simple";
  };
  "routes/api.backgrounds.token.tsx": {
    id: "routes/api.backgrounds.token";
    page: "/api/backgrounds/token";
  };
  "routes/api.backgrounds.$id.tsx": {
    id: "routes/api.backgrounds.$id";
    page: "/api/backgrounds/:id" | "/api/backgrounds/:id/activate";
  };
  "routes/api.backgrounds.$id.activate.tsx": {
    id: "routes/api.backgrounds.$id.activate";
    page: "/api/backgrounds/:id/activate";
  };
  "routes/collections.$handle.jsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.jsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/collections._index.jsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/api.admin.config.jsx": {
    id: "routes/api.admin.config";
    page: "/api/admin/config";
  };
  "routes/policies.$handle.jsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.jsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.jsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/api.products-3d.jsx": {
    id: "routes/api.products-3d";
    page: "/api/products-3d";
  };
  "routes/api.test-client.jsx": {
    id: "routes/api.test-client";
    page: "/api/test-client";
  };
  "routes/collections.all.jsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/policies._index.jsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/account_.login.jsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/discount.$code.jsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/favicon[.]ico.jsx": {
    id: "routes/favicon[.]ico";
    page: "/favicon.ico";
  };
  "routes/pages.$handle.jsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[sitemap.xml].jsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/blogs._index.jsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/[robots.txt].jsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/api.product.jsx": {
    id: "routes/api.product";
    page: "/api/product";
  };
  "routes/api.test-3d.jsx": {
    id: "routes/api.test-3d";
    page: "/api/test-3d";
  };
  "routes/($locale).jsx": {
    id: "routes/($locale)";
    page: "/:locale?" | "/:locale?/blogs/:blogHandle/:articleHandle" | "/:locale?/sitemap/:type/:page.xml" | "/:locale?/blogs/:blogHandle" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/collections" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/collections/all" | "/:locale?/policies" | "/:locale?/account/login" | "/:locale?/discount/:code" | "/:locale?/pages/:handle" | "/:locale?/sitemap.xml" | "/:locale?/blogs" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/:locale?/*";
  };
  "routes/($locale).blogs.$blogHandle.$articleHandle.jsx": {
    id: "routes/($locale).blogs.$blogHandle.$articleHandle";
    page: "/:locale?/blogs/:blogHandle/:articleHandle";
  };
  "routes/($locale).sitemap.$type.$page[.xml].jsx": {
    id: "routes/($locale).sitemap.$type.$page[.xml]";
    page: "/:locale?/sitemap/:type/:page.xml";
  };
  "routes/($locale).blogs.$blogHandle._index.jsx": {
    id: "routes/($locale).blogs.$blogHandle._index";
    page: "/:locale?/blogs/:blogHandle";
  };
  "routes/($locale).collections.$handle.jsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).account_.authorize.jsx": {
    id: "routes/($locale).account_.authorize";
    page: "/:locale?/account/authorize";
  };
  "routes/($locale).collections._index.jsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).policies.$handle.jsx": {
    id: "routes/($locale).policies.$handle";
    page: "/:locale?/policies/:handle";
  };
  "routes/($locale).products.$handle.jsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).account_.logout.jsx": {
    id: "routes/($locale).account_.logout";
    page: "/:locale?/account/logout";
  };
  "routes/($locale).collections.all.jsx": {
    id: "routes/($locale).collections.all";
    page: "/:locale?/collections/all";
  };
  "routes/($locale).policies._index.jsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/($locale).account_.login.jsx": {
    id: "routes/($locale).account_.login";
    page: "/:locale?/account/login";
  };
  "routes/($locale).discount.$code.jsx": {
    id: "routes/($locale).discount.$code";
    page: "/:locale?/discount/:code";
  };
  "routes/($locale).pages.$handle.jsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).[sitemap.xml].jsx": {
    id: "routes/($locale).[sitemap.xml]";
    page: "/:locale?/sitemap.xml";
  };
  "routes/($locale).blogs._index.jsx": {
    id: "routes/($locale).blogs._index";
    page: "/:locale?/blogs";
  };
  "routes/($locale).account.jsx": {
    id: "routes/($locale).account";
    page: "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*";
  };
  "routes/($locale).account.orders._index.jsx": {
    id: "routes/($locale).account.orders._index";
    page: "/:locale?/account/orders";
  };
  "routes/($locale).account.orders.$id.jsx": {
    id: "routes/($locale).account.orders.$id";
    page: "/:locale?/account/orders/:id";
  };
  "routes/($locale).account.addresses.jsx": {
    id: "routes/($locale).account.addresses";
    page: "/:locale?/account/addresses";
  };
  "routes/($locale).account.profile.jsx": {
    id: "routes/($locale).account.profile";
    page: "/:locale?/account/profile";
  };
  "routes/($locale).account._index.jsx": {
    id: "routes/($locale).account._index";
    page: "/:locale?/account";
  };
  "routes/($locale).account.$.jsx": {
    id: "routes/($locale).account.$";
    page: "/:locale?/account/*";
  };
  "routes/($locale).search.jsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale)._index.jsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).cart.jsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.$lines.jsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/($locale).$.jsx": {
    id: "routes/($locale).$";
    page: "/:locale?/*";
  };
  "routes/api.page.jsx": {
    id: "routes/api.page";
    page: "/api/page";
  };
  "routes/account.jsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.jsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.jsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.jsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.jsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.jsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.jsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/search.jsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.jsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.jsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
};