name: Deploy to Oxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shopify Oxygen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Shopify Hydrogen Deploy
        run: npx shopify hydrogen deploy
        env:
          SHOPIFY_CLI_ACCEPT_LICENSE: 1